import { useEffect, useState } from 'react';
import { BarChart3, CalendarClock, ChevronRight, CircleDollarSign, FolderKanban, Gauge, KeyRound, LayoutDashboard, MessageSquareText, PenLine, Plus, Search, Send, Sparkles, Star, Target, Trash2, TrendingUp, Users, X } from 'lucide-react';

const api = {
  get: async (url: string) => request('GET', url),
  post: async (url: string, body?: unknown) => request('POST', url, body),
  delete: async (url: string) => request('DELETE', url)
};
async function request(method: string, url: string, body?: unknown) {
  const response = await fetch(url, {
    method,
    headers: body === undefined ? undefined : {'Content-Type':'application/json'},
    body: body === undefined ? undefined : JSON.stringify(body)
  });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Request failed');
  return {data};
}
type Tool={id:string;label:string;icon:any;desc:string};
const tools:Tool[]=[
{id:'gig',label:'Gig Analyzer',icon:Gauge,desc:'Score your gig and uncover conversion gaps.'},
{id:'proposal',label:'Proposal Generator',icon:Send,desc:'Write tailored proposals that sound human.'},
{id:'reply',label:'Client Reply',icon:MessageSquareText,desc:'Turn client messages into confident replies.'},
{id:'keywords',label:'Keyword Research',icon:KeyRound,desc:'Find focused search terms and listing angles.'},
{id:'description',label:'Gig Description',icon:PenLine,desc:'Build clear, benefit-led gig copy.'},
{id:'portfolio',label:'Portfolio Generator',icon:FolderKanban,desc:'Turn project details into portfolio case studies.'},
{id:'earnings',label:'Earnings Tracker',icon:CircleDollarSign,desc:'Track income, targets, and momentum.'},
{id:'crm',label:'Client CRM',icon:Users,desc:'Keep leads, active clients, and history organized.'},
{id:'reminders',label:'Follow-up Reminders',icon:CalendarClock,desc:'Never forget a warm lead or pending reply.'},
{id:'reviews',label:'Review Request',icon:Star,desc:'Ask for reviews without sounding pushy.'}
];
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});

function App(){
 const[active,setActive]=useState('overview'),[openTool,setOpenTool]=useState<string|null>(null),[records,setRecords]=useState<any[]>([]),[earnings,setEarnings]=useState<any[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
 const load=async()=>{try{const[crm,income]=await Promise.all([api.get('/api/crm'),api.get('/api/earnings')]);setRecords(crm.data.items||[]);setEarnings(income.data.items||[])}catch{setNotice('Could not load saved workspace data.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const total=earnings.reduce((s,e)=>s+Number(e.amount||0),0),activeClients=records.filter(r=>r.status==='Active').length,pipeline=records.filter(r=>r.status==='Lead').reduce((s,r)=>s+Number(r.value||0),0);
 const title=active==='overview'?'Good evening, freelancer.':tools.find(t=>t.id===active)?.label||'Workspace';
 const subtitle=active==='overview'?'Your business at a glance — then jump into the work that moves revenue.':tools.find(t=>t.id===active)?.desc;
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brandMark"><Sparkles size={17}/></div><div>Freelance<span>Pilot</span></div></div><div className="workspace"><div className="avatar">L</div><div><strong>My Workspace</strong><small>Solo freelancer</small></div><ChevronRight size={15}/></div><nav><button className={active==='overview'?'nav active':'nav'} onClick={()=>setActive('overview')}><LayoutDashboard size={17}/> Overview</button><div className="navLabel">AI TOOLS</div>{tools.slice(0,6).map(t=><button key={t.id} className={active===t.id?'nav active':'nav'} onClick={()=>{setActive(t.id);setOpenTool(t.id)}}><t.icon size={17}/>{t.label}</button>)}<div className="navLabel">BUSINESS</div>{tools.slice(6).map(t=><button key={t.id} className={active===t.id?'nav active':'nav'} onClick={()=>setActive(t.id)}><t.icon size={17}/>{t.label}</button>)}</nav><div className="sidebarBottom"><div className="plan"><b>Free workspace</b><small>8 AI generations left</small><button>Upgrade</button></div><div className="userLine"><div className="avatar small">L</div><span>Freelancer</span><span className="dot"/></div></div></aside><main className="main"><header className="topbar"><div className="crumb">Workspace <ChevronRight size={13}/> {active==='overview'?'Overview':tools.find(t=>t.id===active)?.label}</div><div className="topActions"><button className="iconBtn"><Search size={17}/></button><button className="help">?</button><button className="primary smallBtn" onClick={()=>setOpenTool('proposal')}><Plus size={16}/> New proposal</button></div></header><section className="content"><div className="pageHead"><div><p className="eyebrow">TUESDAY, AUGUST 11</p><h1>{title}</h1><p>{subtitle}</p></div><div className="status"><span className="liveDot"/> All systems ready</div></div>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}><X size={15}/></button></div>}{active==='overview'?<Overview total={total} activeClients={activeClients} pipeline={pipeline} records={records} earnings={earnings} loading={loading} onTool={(id:string)=>{setActive(id);setOpenTool(id)}}/>:active==='earnings'?<Earnings earnings={earnings} total={total} onRefresh={load}/>:active==='crm'?<CRM records={records} onRefresh={load}/>:<ToolPage id={active}/>}</section></main>{openTool&&<ToolModal id={openTool} onClose={()=>setOpenTool(null)}/>}</div>
}
function Overview({total,activeClients,pipeline,records,earnings,loading,onTool}:any){return <><div className="stats"><Stat label="This month" value={money.format(total)} trend="+18.4%" icon={CircleDollarSign}/><Stat label="Active clients" value={String(activeClients||0)} trend="+2" icon={Users}/><Stat label="Lead pipeline" value={money.format(pipeline)} trend="Warm" icon={Target}/><Stat label="Win rate" value="32%" trend="+6.2%" icon={TrendingUp}/></div><div className="grid2"><section className="card aiHub"><div className="sectionTitle"><div><p className="eyebrow">AI COMMAND CENTER</p><h2>What are you working on?</h2></div><Sparkles size={20}/></div><p className="muted">Choose a workflow and FreelancePilot will turn your raw input into client-ready work.</p><div className="toolGrid">{tools.slice(0,6).map(t=><button key={t.id} className="toolCard" onClick={()=>onTool(t.id)}><div className="toolIcon"><t.icon size={18}/></div><div><b>{t.label}</b><small>{t.desc}</small></div><ChevronRight size={15}/></button>)}</div></section><section className="card"><div className="sectionTitle"><div><p className="eyebrow">FOLLOW-UPS</p><h2>Today</h2></div></div><div className="followList"><Follow name="Marcus · Web app" meta="Proposal sent · 2 days ago" due="Due today"/><Follow name="Sarah · FiveM server" meta="Asked for pricing" due="Due today"/><Follow name="Jordan · DayZ" meta="Completed order" due="Tomorrow"/></div></section></div><div className="grid2 lower"><section className="card"><div className="sectionTitle"><div><p className="eyebrow">RECENT CLIENTS</p><h2>Pipeline</h2></div></div>{loading?<div className="empty">Loading workspace…</div>:records.length?records.slice(0,4).map((r:any)=><div className="row" key={r.id}><div className="avatar client">{String(r.name||'C')[0]}</div><div className="rowMain"><b>{r.name}</b><small>{r.service||'Freelance project'}</small></div><span className={'pill '+String(r.status).toLowerCase()}>{r.status}</span><b>{money.format(Number(r.value||0))}</b></div>):<div className="empty">No clients yet.</div>}</section><section className="card"><div className="sectionTitle"><div><p className="eyebrow">EARNINGS</p><h2>Recent income</h2></div></div>{earnings.length?earnings.slice(-4).reverse().map((e:any)=><div className="row" key={e.id}><div className="miniIcon"><CircleDollarSign size={15}/></div><div className="rowMain"><b>{e.title}</b><small>{e.platform} · {e.date}</small></div><strong className="income">+{money.format(Number(e.amount||0))}</strong></div>):<div className="empty">No earnings logged yet.</div>}</section></div></>}
function Stat({label,value,trend,icon:Icon}:any){return <div className="stat card"><div className="miniIcon"><Icon size={17}/></div><small>{label}</small><strong>{value}</strong><span>{trend}</span></div>}
function Follow({name,meta,due}:any){return <div className="follow"><div className="check"/><div><b>{name}</b><small>{meta}</small></div><span>{due}</span></div>}
function ToolPage({id}:{id:string}){return <div className="card workspaceCard"><div className="largeTool"><div className="heroIcon"><Sparkles size={25}/></div><div><h2>{tools.find(t=>t.id===id)?.label}</h2><p>{tools.find(t=>t.id===id)?.desc}</p></div></div><ToolForm id={id}/></div>}
function ToolForm({id}:{id:string}){const[input,setInput]=useState(''),[result,setResult]=useState(''),[busy,setBusy]=useState(false);const placeholder:any={gig:'Paste your Fiverr or Upwork gig title and description…',proposal:'Paste the job post and tell us why you are a fit…',reply:'Paste the client message you need to answer…',keywords:'Enter your service, niche, and target marketplace…',description:'Describe your service, audience, deliverables, and differentiators…',portfolio:'Describe the project, problem, solution, tools, and result…',reviews:'Describe the completed project and the relationship with the client…',reminders:'Add the client, follow-up reason, and preferred date…'};const go=async()=>{if(!input.trim())return;setBusy(true);try{const r=await api.post('/api/generate',{tool:id,input});setResult(r.data.text||'No result returned.')}catch(e:any){setResult(e.message||'Generation failed. Please try again.')}finally{setBusy(false)}};return <div className="formArea"><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={placeholder[id]||'Tell FreelancePilot what you need…'}/><div className="formFooter"><span>{input.length} characters</span><button className="primary" disabled={busy||!input.trim()} onClick={go}><Sparkles size={16}/>{busy?'Generating…':'Generate with AI'}</button></div>{result&&<div className="result"><div className="resultHead"><b>Generated result</b><button onClick={()=>navigator.clipboard.writeText(result)}>Copy</button></div><pre>{result}</pre></div>}</div>}
function ToolModal({id,onClose}:{id:string;onClose:()=>void}){return <div className="modalBackdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">AI WORKFLOW</span><h2>{tools.find(t=>t.id===id)?.label}</h2></div><button className="iconBtn" onClick={onClose}><X size={18}/></button></div><ToolForm id={id}/></div></div>}
function Earnings({earnings,total,onRefresh}:{earnings:any[];total:number;onRefresh:()=>void}){const[title,setTitle]=useState(''),[amount,setAmount]=useState(''),[platform,setPlatform]=useState('Fiverr');const add=async()=>{if(!title||!amount)return;await api.post('/api/earnings',{title,amount:Number(amount),platform,date:new Date().toISOString().slice(0,10)});setTitle('');setAmount('');onRefresh()};return <div className="card workspaceCard"><div className="sectionTitle"><div><p className="eyebrow">MONEY</p><h2>Earnings tracker</h2><p className="muted">Current tracked earnings: <b>{money.format(total)}</b></p></div></div><div className="inlineForm"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Project / order name"/><input value={amount} onChange={e=>setAmount(e.target.value)} type="number" placeholder="Amount"/><select value={platform} onChange={e=>setPlatform(e.target.value)}><option>Fiverr</option><option>Upwork</option><option>Direct</option></select><button className="primary" onClick={add}><Plus size={16}/> Add</button></div><div className="table">{earnings.map(e=><div className="row" key={e.id}><div className="miniIcon"><CircleDollarSign size={15}/></div><div className="rowMain"><b>{e.title}</b><small>{e.platform} · {e.date}</small></div><strong className="income">+{money.format(Number(e.amount))}</strong></div>)}</div></div>}
function CRM({records,onRefresh}:{records:any[];onRefresh:()=>void}){const[name,setName]=useState(''),[service,setService]=useState(''),[value,setValue]=useState('');const add=async()=>{if(!name)return;await api.post('/api/crm',{name,service,value:Number(value||0),status:'Lead'});setName('');setService('');setValue('');onRefresh()};const del=async(id:string)=>{await api.delete('/api/crm/'+id);onRefresh()};return <div className="card workspaceCard"><div className="sectionTitle"><div><p className="eyebrow">RELATIONSHIPS</p><h2>Client CRM</h2><p className="muted">One place for leads, active clients, and project value.</p></div></div><div className="inlineForm"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Client name"/><input value={service} onChange={e=>setService(e.target.value)} placeholder="Service / project"/><input value={value} onChange={e=>setValue(e.target.value)} type="number" placeholder="Value"/><button className="primary" onClick={add}><Plus size={16}/> Add client</button></div><div className="table">{records.length?records.map(r=><div className="row" key={r.id}><div className="avatar client">{String(r.name)[0]}</div><div className="rowMain"><b>{r.name}</b><small>{r.service}</small></div><span className={'pill '+String(r.status).toLowerCase()}>{r.status}</span><b>{money.format(Number(r.value||0))}</b><button className="iconBtn danger" onClick={()=>del(r.id)}><Trash2 size={15}/></button></div>):<div className="empty">Your CRM is empty. Add a lead above.</div>}</div></div>}
export default App;